name: ci

on:
  push:
    branches:
    - master
    - testing
  pull_request:
    branches:
    - master
    - testing

jobs:
  golang:
    name: Golang compile and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install libpcap
      run: sudo apt-get install -y libpcap-dev

    - name: Build
      working-directory: ./src
      run: go build -v ./...

    - name: Test
      working-directory: ./src
      run: go test -v ./...

  docker:
    name: Functional test in docker compose
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Start containers
      run: docker compose -f "docker-compose.yml" -p router up -d --build

        
    - name: ping-test.sh
      run: ./tests/test_router.sh
    

    - name: Stop containers
      if: always()
      run: docker compose -f "docker-compose.yml" -p router down
